package com.demo.model;
// Generated Oct 27, 2021, 8:24:59 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "accountbank1")
public class Transaction implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Date date;
	private double transmoney;
	private int transtype;

	public Transaction() {
	}

	public Transaction(Account account, Date date, double transmoney, int transtype) {
		this.account = account;
		this.date = date;
		this.transmoney = transmoney;
		this.transtype = transtype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idacc", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "transmoney", nullable = false, precision = 22, scale = 0)
	public double getTransmoney() {
		return this.transmoney;
	}

	public void setTransmoney(double transmoney) {
		this.transmoney = transmoney;
	}

	@Column(name = "transtype", nullable = false)
	public int getTranstype() {
		return this.transtype;
	}

	public void setTranstype(int transtype) {
		this.transtype = transtype;
	}

}
