package com.demo.models;
// Generated 09:26:24 23-01-2022 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AccountRole generated by hbm2java
 */
@Entity
@Table(name = "account_role", catalog = "_qlhtk")
public class AccountRole implements java.io.Serializable {

	private AccountRoleId id;

	public AccountRole() {
	}

	public AccountRole(AccountRoleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idAcc", column = @Column(name = "id_acc", nullable = false)),
			@AttributeOverride(name = "idRole", column = @Column(name = "id_role", nullable = false)) })
	public AccountRoleId getId() {
		return this.id;
	}

	public void setId(AccountRoleId id) {
		this.id = id;
	}

}
