package com.demo.models;
// Generated 09:26:24 23-01-2022 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountRoleId generated by hbm2java
 */
@Embeddable
public class AccountRoleId implements java.io.Serializable {

	private int idAcc;
	private int idRole;

	public AccountRoleId() {
	}

	public AccountRoleId(int idAcc, int idRole) {
		this.idAcc = idAcc;
		this.idRole = idRole;
	}

	@Column(name = "id_acc", nullable = false)
	public int getIdAcc() {
		return this.idAcc;
	}

	public void setIdAcc(int idAcc) {
		this.idAcc = idAcc;
	}

	@Column(name = "id_role", nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountRoleId))
			return false;
		AccountRoleId castOther = (AccountRoleId) other;

		return (this.getIdAcc() == castOther.getIdAcc()) && (this.getIdRole() == castOther.getIdRole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAcc();
		result = 37 * result + this.getIdRole();
		return result;
	}

}
