package com.demo.models;
// Generated 09:26:24 23-01-2022 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "_qlhtk")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private double price;
	private int quantity;
	private int status;
	private String description;
	private Date created;
	private String namePhoto;
	private Set<ImportInvoices> importInvoiceses = new HashSet<ImportInvoices>(0);
	private Set<ExportInvoice> exportInvoices = new HashSet<ExportInvoice>(0);

	public Product() {
	}

	public Product(Category category, String name, double price, int quantity, int status, String description,
			Date created, String namePhoto) {
		this.category = category;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.status = status;
		this.description = description;
		this.created = created;
		this.namePhoto = namePhoto;
	}

	public Product(Category category, String name, double price, int quantity, int status, String description,
			Date created, String namePhoto, Set<ImportInvoices> importInvoiceses, Set<ExportInvoice> exportInvoices) {
		this.category = category;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.status = status;
		this.description = description;
		this.created = created;
		this.namePhoto = namePhoto;
		this.importInvoiceses = importInvoiceses;
		this.exportInvoices = exportInvoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "name_photo", nullable = false, length = 250)
	public String getNamePhoto() {
		return this.namePhoto;
	}

	public void setNamePhoto(String namePhoto) {
		this.namePhoto = namePhoto;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "product_invoice_import", catalog = "_qlhtk", joinColumns = {
			@JoinColumn(name = "id_pro", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_invoice", nullable = false, updatable = false) })
	public Set<ImportInvoices> getImportInvoiceses() {
		return this.importInvoiceses;
	}

	public void setImportInvoiceses(Set<ImportInvoices> importInvoiceses) {
		this.importInvoiceses = importInvoiceses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "product_invoice_export", catalog = "_qlhtk", joinColumns = {
			@JoinColumn(name = "id_pro", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_invoice", nullable = false, updatable = false) })
	public Set<ExportInvoice> getExportInvoices() {
		return this.exportInvoices;
	}

	public void setExportInvoices(Set<ExportInvoice> exportInvoices) {
		this.exportInvoices = exportInvoices;
	}

}
